// The OCR parsers against (1) the hand-written cases of test_am.py and (2) every archived frame in data/shots, where the
// oracle is what am.py's parsers say (parse-parity.json, regenerated by the script in its "_" key) and the DB agrees.
import XCTest
@testable import Ppomi

final class OCRTests: XCTestCase {
    /// Words as `phone ocr` emits them, one per row.
    func W(_ texts: [String], y0: Double = 0.30) -> [OCR.Word] {
        texts.enumerated().map { OCR.Word(x: 0.1, y: y0 + 0.03 * Double($0.0), w: 0.4, h: 0.012, text: $0.1) }
    }
    func bal(_ texts: [String], _ app: String) -> [String] { OCR.balances(W(texts), account: OCR.account[app]!).map { "\($0.0)=\($0.1)" } }
    let now = TS.parse("2026-09-02 17:00")!

    func testBalancesKB() {
        XCTAssertEqual(OCR.balances([
            OCR.Word(x: 0.17, y: 0.38, w: 0.4, h: 0.012, text: "KB국민ONE통장-보통예금 (3456) D"),
            OCR.Word(x: 0.81, y: 0.385, w: 0.06, h: 0.012, text: "이체"),
            OCR.Word(x: 0.17, y: 0.40, w: 0.2, h: 0.014, text: "518,574원"),
            OCR.Word(x: 0.25, y: 0.34, w: 0.4, h: 0.012, text: "WOW! 와우회원은 매 주문 배달비 0원"),
        ], account: OCR.account["KB"]!).map { "\($0.0)=\($0.1)" }, ["KB국민ONE통장-보통예금 (****)=518574"])
        XCTAssertEqual(bal(["KB국민ONE통장-", "보통예금 (3456)", "518,574원"], "KB"), ["보통예금 (****)=518574"])
        XCTAssertEqual(bal(["내 계좌 전체보기", "KB국민ONE통장 (3456)", "518,574원"], "KB"), ["KB국민ONE통장 (****)=518574"])
        XCTAssertEqual(bal(["KB국민ONE통장 (3456)", "518,574원", "KB마이너스통장 (9876)", "-1,234,567원"], "KB"),
                       ["KB국민ONE통장 (****)=518574", "KB마이너스통장 (****)=-1234567"])
        XCTAssertEqual(bal(["KB국민ONE통장 (3456)", "KB카드쓰담적금 출시 기념 최대 100만원", "518,574원"], "KB"), ["KB국민ONE통장 (****)=518574"])
        XCTAssertEqual(bal(["KB국민ONE통장 (3456) 518,574원", "KB적금 (7777) 1,000,000원"], "KB"),
                       ["KB국민ONE통장 (****)=518574", "KB적금 (****)=1000000"])
        XCTAssertEqual(bal(["총 잔액", "9,999,999원", "모으기 이체", "예금 • 적금 9,999,999원",
                            "KB국민ONE통장-보통예금 :", "123456-01-654321 D", "518,574원",
                            "KB마음편한통장 :", "123456-02-654321 D", "1,000원",
                            "직장인우대적금 :", "123456-03-654321 G", "신규일 2023.10.24", "만기일 2026.10.24 (D-52)", "3,000,000원"], "KB"),
                       ["KB국민ONE통장-보통예금 …4321=518574", "KB마음편한통장 …4321=1000", "직장인우대적금 …4321=3000000"])
    }

    func testBalancesTossKakaoKbank() {
        XCTAssertEqual(bal(["3개 계좌 1,518,574원", "토스뱅크 통장 (1234)", "518,574원"], "TOSS"), ["토스뱅크 통장 (****)=518574"])
        XCTAssertEqual(bal(["길동님의 9월 최대 적립금 확인하기", "12,345원", "0원 송금", "토스뱅크 통장", "다시 연결하기 송금",
                            "입출금통장 • 만료", "계좌 대출 카드 모두보기", "0원 내역"], "TOSS"), [])
        XCTAssertEqual(bal(["A I 관련 지출 통장 *", "700,000원", "카드 이체"], "KAKAO"), ["AI 관련 지출 통장=700000"])
        XCTAssertEqual(bal(["A| 관련 지출 통장 *", "700,000원", "카드 이체"], "KAKAO"), ["AI 관련 지출 통장=700000"])
        XCTAssertEqual(bal(["^ AI 관련 지출 통장", "3333-01-1234567 C", "700,000원"], "KAKAO"), ["AI 관련 지출 통장=700000"])
        XCTAssertEqual(bal(["MY 입출금통장 100-000-654321 D :", "123원", "가져오기 이체하기", "계좌", "WINGO 통장 이체", "1,000,000원"], "KBANK"),
                       ["MY 입출금통장 …4321=123", "WINGO 통장=1000000"])
    }

    func testKakaoTransactions() {
        let tx = OCR.transactions(["^ AI 관련 지출 통장", "3333-02-1234567 C", "518,574원", "Q 3개월 • 전체 • 최신순 ✓",
                                   "AI 이체의 새로운 방법", "09.02",
                                   "쿠팡이츠 -12,345원", "15:50 #체크카드 518,574원",
                                   "이디야커피 IBK고객 -4,500원", "13:06 #체크카드 530,919원",
                                   "월급 +1,000,000원", "09:00 #입금 535,419원",
                                   "12.31", "GS25 -1,000원", "23:59 #체크카드 100원"], when: now, app: "KAKAO")
        XCTAssertEqual(tx.map { "\($0.ts) \($0.kind) \($0.amount) \($0.merchant) \($0.cumulative)" }, [
            "2026-09-02 15:50 approval 12345 쿠팡이츠 518574", "2026-09-02 13:06 approval 4500 이디야커피 IBK고객 530919",
            "2026-09-02 09:00 deposit 1000000 월급 535419", "2025-12-31 23:59 approval 1000 GS25 100"])   // 12.31 read in September is last year
        XCTAssertEqual(Set(tx.map(\.uid)).count, 4)
        // rows accumulate across scrolled pages: page 2 has no date header and a merchant/time pair straddles the boundary
        let p1 = ["09.02", "가맹점1 -1,000원", "18:00 #체크카드 9,000원", "가맹점2 -1,000원"]
        let p2 = ["17:00 #체크카드 10,000원", "가맹점3 -1,000원", "16:00 #체크카드 11,000원", "09.01 :", "가맹점4 -2,000원", "21:00 #체크카드 13,000원"]
        XCTAssertEqual(OCR.transactions(p1 + p2, when: now, app: "KAKAO").map { "\($0.ts) \($0.merchant)" },
                       ["2026-09-02 18:00 가맹점1", "2026-09-02 17:00 가맹점2", "2026-09-02 16:00 가맹점3", "2026-09-01 21:00 가맹점4"])
        // a scrolled page opens with the rows that sat just above its first date header on the previous page: they keep the newer date
        let q1 = ["09.01", "가맹점A -1,000원", "22:48 #체크카드 64,041원", "08.31", "가맹점B -2,000원", "23:24 #체크카드 979,417원"]
        let q2 = ["가맹점A -1,000원", "22:48 #체크카드 64,041원", "08.31", "가맹점B -2,000원", "23:24 #체크카드 979,417원", "가맹점C -3,000원", "19:06 #체크카드 348,770원"]
        XCTAssertEqual(OCR.transactions([OCR.page] + q1 + [OCR.page] + q2, when: now, app: "KAKAO").map { "\($0.ts) \($0.merchant)" },
                       ["2026-09-01 22:48 가맹점A", "2026-08-31 23:24 가맹점B", "2026-09-01 22:48 가맹점A", "2026-08-31 23:24 가맹점B", "2026-08-31 19:06 가맹점C"])
        // the natural key ignores OCR drift in the merchant text, a tag with a space still parses, '-' with 취소 in the name is spend
        let a = OCR.transactions(["09.02", "이디야커피 IBK고객 -4,500원", "13:06 #체크카드 530,919원"], when: now, app: "KAKAO")[0]
        let b = OCR.transactions(["09.02", "이디야커피 I BK고객 -4,500원", "13:06 # 체크카드 530,919원"], when: now, app: "KAKAO")[0]
        XCTAssertEqual(a.uid, b.uid); XCTAssertEqual(b.card, "체크카드")
        XCTAssertEqual(a.uid, "KAKAO:2026-09-02 13:06:-4500:530919")
        let c1 = OCR.transactions(["09.02", "취소마트 -3,000원", "12:00 #체크카드 1,000원", "쿠팡 +3,000원", "12:30 #체크카드 취소 4,000원"], when: now, app: "KAKAO")
        XCTAssertEqual(c1.map(\.kind), ["approval", "cancel"])
        // deposits carry no sign and (transfers in) no tag; interest has a tag; OCR sometimes reads '-' as '~'
        let d = OCR.transactions(["08.30", "CURSOR USAGE MID AU -155,934원", "22:59 #체크카드 989,222원", "홍길동 1,000,000원", "22:59 1,145,156원",
                                  "입출금통장 이자 40원", "04:29 #예금이자 1,087,310원", "CURSOR USAGE AUG ~152,308원", "14:12 #체크카드 913,102원"], when: now, app: "KAKAO")
        XCTAssertEqual(d.map { "\($0.kind) \($0.amount) \($0.merchant) [\($0.card)] \($0.cumulative)" }, [
            "approval 155934 CURSOR USAGE MID AU [체크카드] 989222", "deposit 1000000 홍길동 [] 1145156",
            "deposit 40 입출금통장 이자 [예금이자] 1087310", "approval 152308 CURSOR USAGE AUG [체크카드] 913102"])
    }

    func testKBTransactions() {
        let kb = OCR.kbTransactions(["< 거래내역조회 =", "KB국민ONE통장 >", "123456-04-123456 V", "518,574원", "출금가능금액 518,574원",
                                     "2026.06.04 ~ 2026.09.03 잔액표기", "2026.08",
                                     "08.24 21:56:29 | 스마트출금", "홍길동", "-100,000원", "518,574원",
                                     "08.10 15:00:56 | ATM", "ATM입금", "+300,000원", "818,574원",
                                     "08.05 09:00:00 I 체크카드", "스타벅스", "~4,500원", "518,574원",
                                     "08.03 10:00:00 | 체크카드취소", "스타벅스", "+4,500원", "523,074원",
                                     "08.01 12:00:00 | 스마트출금",
                                     "< 거래내역조회 =", "518,574원",
                                     "08.01 12:00:00 | 스마트출금", "홍길동", "-50,000원", "518,574원",
                                     "2025.12", "12.31 23:59:00 | 예금이자", "이자", "+10원", "100원"], when: now, app: "KB")
        XCTAssertEqual(kb.map { "\($0.ts) \($0.kind) \($0.amount) \($0.merchant) [\($0.card)] \($0.cumulative)" }, [
            "2026-08-24 21:56 withdrawal 100000 홍길동 [스마트출금] 518574", "2026-08-10 15:00 deposit 300000 ATM입금 [ATM] 818574",
            "2026-08-05 09:00 approval 4500 스타벅스 [체크카드] 518574", "2026-08-03 10:00 cancel 4500 스타벅스 [체크카드취소] 523074",
            "2026-08-01 12:00 withdrawal 50000 홍길동 [스마트출금] 518574", "2025-12-31 23:59 deposit 10 이자 [예금이자] 100"])
        XCTAssertEqual(Set(kb.map(\.uid)).count, 6)
    }

    // ---------------------------------------------------------------- parity over the archived frames
    static let shots = URL(fileURLWithPath: LedgerTests.dbPath).deletingLastPathComponent().appendingPathComponent("shots")
    static let fixture = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("parse-parity.json")

    func oracle() throws -> [String: Any] {
        guard FileManager.default.fileExists(atPath: Self.shots.path), let d = try? Data(contentsOf: Self.fixture)
        else { throw XCTSkip("no data/shots or parse-parity.json") }
        return try JSONSerialization.jsonObject(with: d) as! [String: Any]
    }
    /// Only the frames the oracle saw: data/shots keeps growing after parse-parity.json was generated.
    func frames() -> [URL] {
        let cut = (try? Self.fixture.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate) ?? .distantFuture
        return ((try? FileManager.default.contentsOfDirectory(at: Self.shots, includingPropertiesForKeys: nil)) ?? [])
            .filter { $0.pathExtension == "jsonl" && when($0.lastPathComponent) <= cut }.sorted { $0.lastPathComponent < $1.lastPathComponent }
    }
    func when(_ name: String) -> Date {
        let f = DateFormatter(); f.locale = Locale(identifier: "en_US_POSIX"); f.dateFormat = "yyyyMMdd-HHmmss"
        return f.date(from: String(name.prefix(15)))!
    }

    /// Same runs (list frames grouped by app, <2 min apart) and, per run, the same transactions in the same order as am.py.
    func testTransactionParityWithPython() throws {
        let o = try oracle()
        var found: [(when: Date, app: String, rows: [String], name: String)] = []
        for j in frames() {
            let rows = OCR.rows(OCR.words(jsonl: j))
            for (app, marker) in OCR.listMarkers.sorted(by: { $0.key < $1.key }) where rows.filter({ marker.match($0) != nil }).count >= 2 {
                found.append((when(j.lastPathComponent), app, rows, j.lastPathComponent))
            }
        }
        var runs: [(app: String, frames: [String], tx: [OCR.Tx])] = [], run: [(when: Date, app: String, rows: [String], name: String)] = []
        for f in found.map(Optional.some) + [nil] {
            if !run.isEmpty, f == nil || f!.app != run.last!.app || f!.when.timeIntervalSince(run.last!.when) > 120 {
                let rows = run.flatMap { [OCR.page] + $0.rows }
                runs.append((run[0].app, run.map(\.name), OCR.parse(app: run[0].app, rows: rows, when: run.last!.when)))
                run = []
            }
            if let f { run.append(f) }
        }
        let py = o["runs"] as! [[String: Any]]
        XCTAssertEqual(runs.count, py.count, "run count")
        for (s, p) in zip(runs, py) {
            XCTAssertEqual(s.app, p["app"] as? String); XCTAssertEqual(s.frames, p["frames"] as? [String])
            let want = (p["tx"] as! [[String: Any]]).map { "\($0["uid"]!) \($0["ts"]!) \($0["kind"]!) \($0["amount"]!) \($0["merchant"]!) [\($0["card"]!)] \($0["cumulative"]!)" }
            let got = s.tx.map { "\($0.uid) \($0.ts) \($0.kind) \($0.amount) \($0.merchant) [\($0.card)] \($0.cumulative)" }
            XCTAssertEqual(got, want, "run \(s.frames.first ?? "")")
        }
        // and the DB, which am.py reparse filled from the same frames, holds exactly these uids
        let db = Set((o["db"] as! [[String: Any]]).map { $0["uid"] as! String })
        XCTAssertEqual(Set(runs.flatMap { $0.tx.map(\.uid) }), db)
    }

    /// Every frame, every app's account pattern: the same (label, balance) list as am.py.
    func testBalanceParityWithPython() throws {
        let o = try oracle()
        var want: [String: [String]] = [:]
        for b in o["balances"] as! [[String: Any]] {
            want["\(b["frame"]!)|\(b["app"]!)"] = (b["found"] as! [[Any]]).map { "\($0[0])=\($0[1])" }
        }
        var got: [String: [String]] = [:]
        for j in frames() {
            let words = OCR.words(jsonl: j)
            for (app, re) in OCR.account {
                let r = OCR.balances(words, account: re).map { "\($0.0)=\($0.1)" }
                if !r.isEmpty { got["\(j.lastPathComponent)|\(app)"] = r }
            }
        }
        XCTAssertEqual(got.count, want.count)
        for (k, w) in want { XCTAssertEqual(got[k], w, k) }
    }
}
